package edu.miu.cs425.mumsched.domain;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.io.Serializable;
import java.sql.Date;
import java.util.Set;

/**
 * @author Demisew Mokonnen, Dereje Enkossa, Tsegaye Beza, Bekalu Assegid
 * @2020
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
public class Schedule implements Serializable {
    @Id
    @GeneratedValue
    private Integer id;
    private Date generatedDate;
    private Date approvedDate;
//    private ScheduleStatus status;//should be an enum
    //entry of the schedule
    @OneToOne(mappedBy = "schedule",cascade = {CascadeType.PERSIST,CascadeType.MERGE})
    private Entry entry;
    //sections that was generated by this schedule
    @OneToMany(mappedBy = "schedule",cascade = CascadeType.ALL)
    private Set<Section> sections;

}
